name       : xorg-driver-video-cirrus
version    : 1.5.3
release    : 15
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-cirrus-1.5.3.tar.gz : 4ff2024c1645f30931f0871f36484aed85ef35aa04852faa7082dbf4ee2c83a5
license    :
    - MIT
summary    : Cirrus Video Driver
component  : xorg.driver
description: |
    The Xorg Cirrus Driver package contains the X.Org Video Driver for Cirrus Logic video chips. Qemu uses this driver for its virtual GPU.
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   :
    - no-bind-now
    - no-symbolic
libsplit   : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
