name       : xorg-driver-video-cirrus
version    : 1.5.3
release    : 18
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-cirrus-1.5.3.tar.gz : 4ff2024c1645f30931f0871f36484aed85ef35aa04852faa7082dbf4ee2c83a5
license    : MIT
component  : xorg.driver
summary    : Cirrus Video Driver
description: |
    The Xorg Cirrus Driver package contains the X.Org Video Driver for Cirrus Logic video chips. Qemu uses this driver for its virtual GPU.
optimize   :
    - no-bind-now
    - no-symbolic
libsplit   : no
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
